### ISSUE TITLE
Looking Glass Icon Remains or Screen Freezes as Soon as Launched

### ISSUE THREAD

**Issue by Sephster** [gnif/LookingGlass#248]
### Required information

Host CPU: AMD Ryzen 5 1600X
Host GPU: AMD Radeon HD 7870
Guest GPU: AMD Radeon RX580
Host Kernel version: 5.5.7
Host QEMU version: 4.2.0

I am running Arch Linux with a Windows 10 guest. Looking-Glass used to work without issue for me but I recently had to switch from my monitor to a television for my main display. Since then, when I launch the VM and run Looking Glass, the screen either remains purple with the looking glass icon, or shows the initial Windows view but the freezes and is non-responsive.

The resolution for my monitor and TV are the same. I don't see any errors appear in the CLI when running Looking Glass. Looking glass in windows doesn't crash during this issue. The CLI output is listed below:

```
➜  ~ looking-glass-client -s -F
[I]               main.c:996  | run                            | Looking Glass (B1-rc6-5-g8ad2d5f949+1)
[I]               main.c:997  | run                            | Locking Method: Atomic
[I]                egl.c:187  | egl_initialize                 | Double buffering is on
[I]                egl.c:201  | egl_initialize                 | Multsampling enabled, max samples: 4
[I]               main.c:902  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1183 | run                            | Using Clipboard: X11
[I]               main.c:1259 | run                            | Waiting for host to signal it's ready...
[I]                egl.c:447  | egl_render_startup             | Vendor  : X.Org
[I]                egl.c:448  | egl_render_startup             | Renderer: AMD PITCAIRN (DRM 2.50.0, 5.5.7-arch1-1, LLVM 9.0.1)
[I]                egl.c:449  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 19.3.4
[I]               main.c:1268 | run                            | Host ready, starting session
```

**Comment by gnif** [comment]
Please provide the host log at `%TEMP%\looking-glass.txt`

**Comment by Sephster** [comment]
Please find the log file attached. Many thanks.

[looking-glass-host.txt](https://github.com/gnif/LookingGlass/files/4309463/looking-glass-host.txt)

**Comment by melynx** [comment]
Similar problem here. This happens after I've updated my Windows 10 VM.

Looking glass would would display the initial frame and basically stops updating. Mouse pointer updates fine and the system is responding.

![screenshot](https://user-images.githubusercontent.com/5338759/76274846-b3e93400-62bc-11ea-85b2-1ce3f9d76e54.png)

**Comment by gnif** [comment]
You are both likely affected by the AcquireLock glitch, please try running the host application with the argument `dxgi:useAcquireLock=true`

**Comment by melynx** [comment]
Hmmm. I've tried using dxgi:useAcquireLock and it doesn't help. The frame still isn't updating as can be seen from the screenshot. Using latest master build.

![image](https://user-images.githubusercontent.com/5338759/77239262-8af96500-6c13-11ea-9716-85fc429af74f.png)

**Comment by parkervcp** [comment]
I too am having this issue.

Host CPU: AMD Ryzen 9 3900X
Host GPU: AMD Radeon Vega 64
Guest GPU: NVIDIA GTX 1080 ti
Host Kernel version: 5.5.10
Host QEMU version: 4.2.0-2

adding the aquirelock fixed the issue. Before that I had the following. I want to specifically call out `KVMFR version missmatch, expected 8 but got 9`

```
[parker@boromir ~]$ looking-glass-client -F -m 75 win:minimizeOnFocusLoss=no -k -s no
[W]             option.c:288  | option_parse                   | Ignored invalid argument: no
[I]               main.c:996  | run                            | Looking Glass (B1-rc6-5-g8ad2d5f949+1)
[I]               main.c:997  | run                            | Locking Method: Atomic
[W]               main.c:1031 | run                            | ================================================================================
[W]               main.c:1032 | run                            | WARNING: The FPS display causes microstutters, this is a known issue
[W]               main.c:1033 | run                            | ================================================================================
[I]                egl.c:187  | egl_initialize                 | Double buffering is on
[I]                egl.c:201  | egl_initialize                 | Multsampling enabled, max samples: 4
[I]               main.c:902  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1183 | run                            | Using Clipboard: X11
[I]               main.c:1259 | run                            | Waiting for host to signal it's ready...
[I]                egl.c:447  | egl_render_startup             | Vendor  : X.Org
[I]                egl.c:448  | egl_render_startup             | Renderer: Radeon RX Vega (VEGA10, DRM 3.36.0, 5.5.10-arch1-1, LLVM 9.0.1)
[I]                egl.c:449  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 19.3.4
[I]               main.c:1268 | run                            | Host ready, starting session
[E]               main.c:1279 | run                            | KVMFR version missmatch, expected 8 but got 9
[E]               main.c:1280 | run                            | This is not a bug, ensure you have the right version of looking-glass-host.exe on the guest
```

**Comment by Sephster** [comment]
Thanks for the response @gnif. I tried the argument but it didn't seem to change anything. This is the output from my console. Host log to follow...

```
➜  ~ looking-glass-client -s -F
[I]               main.c:996  | run                            | Looking Glass (B1-rc6-5-g8ad2d5f949+1)
[I]               main.c:997  | run                            | Locking Method: Atomic
[I]                egl.c:187  | egl_initialize                 | Double buffering is on
[I]                egl.c:201  | egl_initialize                 | Multsampling enabled, max samples: 4
[I]               main.c:902  | try_renderer                   | Using Renderer: EGL
[I]               main.c:1183 | run                            | Using Clipboard: X11
[I]               main.c:1259 | run                            | Waiting for host to signal it's ready...
[I]                egl.c:447  | egl_render_startup             | Vendor  : X.Org
[I]                egl.c:448  | egl_render_startup             | Renderer: AMD PITCAIRN (DRM 2.50.0, 5.5.7-arch1-1, LLVM 9.0.1)
[I]                egl.c:449  | egl_render_startup             | Version : OpenGL ES 3.2 Mesa 19.3.4
[I]               main.c:1268 | run                            | Host ready, starting session
```

There is no further output after the _starting session_ message

**Comment by Sephster** [comment]
[looking-glass-host.txt](https://github.com/gnif/LookingGlass/files/4365604/looking-glass-host.txt)

**Comment by gnif** [comment]
`B1-rc6-5` is one revision behind `B1`. Also a ton has changed since `B1` now, please try bleeding edge and see if this resolves your issue. (be sure to update the host AND the client)

**Comment by Sephster** [comment]
Thanks. I've upgraded to bleeding edge. I now consistently see the desktop but it is frozen on the initial render. Same with and without the dxgi:useAcquireLock argument.

I've attached the latest log. Thanks again for your help with this!
[looking-glass-host.txt](https://github.com/gnif/LookingGlass/files/4370410/looking-glass-host.txt)

**Comment by gnif** [comment]
I have heard this by a few now and I am yet to find the cause, the COVOID-19 outbreak has been taking my attention away from this project at current I am sorry.

**Comment by Sephster** [comment]
No worries @gnif - totally understand. I am a maintainer of an oauth server and covid-19 combined with a new baby has taken away a lot of my free time right now as well. 

No major rush on this. If you need me to run any further tests in the meantime to help you, please just shout.

As I said, the only change in my set up has been moving from a monitor to a TV so I expect this to be related.

**Comment by fatalis** [comment]
This has been occurring for me on everything after B1. I use NvFBC and I've noticed that the opengl renderer gives a black screen and the egl renderer gives a single frame as described.

**Comment by DataBeaver** [comment]
This could be due to the use of a non-volatile variable for inter-thread communication in the client.  The compiler will see that it's not changed in framebuffer_read and the spinlock loop will never terminate.

Patch here: http://www.tdb.fi/~tdb/tmp/0001-Use-a-volatile-pointer-to-read-frame-write-position.patch

For whatever reason I had to restart the host process after fixing the client, but now it seems to work.

**Comment by fatalis** [comment]
@DataBeaver Thanks, fixes EGL for me! OpenGL still doesn't work (doesn't get past the splash screen now) but I'm not sure if the ogl code is up to date.

**Comment by gnif** [comment]
Awesome find, however, it shouldn't be volatile but an atomic.

**Comment by Sephster** [comment]
Would you like me to give this patch a try @gnif?

**Comment by DataBeaver** [comment]
Here's an updated version of the patch which uses atomic: http://www.tdb.fi/~tdb/tmp/0001-Use-an-atomic-type-for-framebuffer-write-position.patch

**Comment by gnif** [comment]
I didn't intend to close this just yet. I have pushed in a variation that is a bit more explicit in memory usage, can you please verify that it has resolved your issue?

**Comment by Sephster** [comment]
Still not working for me with the latest build sorry @gnif. Updated log attached. Problem presenting itself the same as before. Thanks for your ongoing help
[looking-glass-host.txt](https://github.com/gnif/LookingGlass/files/4466740/looking-glass-host.txt)

**Comment by fatalis** [comment]
Latest commit works for me just as with @DataBeaver's patch

**Comment by DataBeaver** [comment]
@gnif's fix works for me as well.

**Comment by gnif** [comment]
@Sephster can you please double-check as everyone both here and elsewhere are reporting that this issue is now fixed for them.

**Comment by DataBeaver** [comment]
@Sephster Could you run the client with gdb and once it's showing a frozen frame, press Ctrl-C to break into the debugger and do `info threads` and `thread apply all backtrace`?  That's how I found it was stuck in the spinlock.

Of course first make sure you've successfully compiled the code after pulling and are running the correct binary.

**Comment by melynx** [comment]
Just to update, working fine here on the latest master (b1-171).

**Comment by Sephster** [comment]
Double checked and still not working for me so I am assuming I'm affected by a different issue. Sometimes I don't even get the first frame. It just stays on the looking glass logo.

I will give gdb a go but I'm not a C dev so haven't used the program before. I suspect I might hit some difficulty with this as I'm not familiar with the tools but will give it a bash and update when I've done so. Cheers

**Comment by fatalis** [comment]
@Sephster Try `-g egl` with master

**Comment by gnif** [comment]
wwww

> @Sephster Try `-g egl` with master and bleeding edge host build

`-g egl` is the default.

**Comment by fatalis** [comment]
> > @Sephster Try `-g egl` with master and bleeding edge host build
> 
> `-g egl` is the default.

yeah but i was thinking he could have an ini set to ogl, and he's getting the exact problem i still get with ogl (looking at his first post though i see that he's using egl now though)

**Comment by DataBeaver** [comment]
There seems to be a logic error in the OpenGL code.  draw_frame() is only called if configure() returns CONFIG_STATUS_OK.  However if a reconfigure wasn't needed it will return CONFIG_STATUS_NOOP and only the mouse pointer will be rendered.  With this patch the OpenGL renderer will update correctly: http://www.tdb.fi/~tdb/tmp/0001-client-render-frame-if-config-didn-t-change.patch

It still regularly logs "Timer drift detected" messages.  I don't know what's up with those.

(As an aside, immediate mode?  Display lists?  The 90s are calling.  Modernizing the code is a whole another discussion though.)

**Comment by gnif** [comment]
The OpenGL code is deprecated in favour of EGL which is modernized, it's only been retained for legacy reasons.

**Comment by gnif** [comment]
Thanks for the fix. Committed in ead09ed1101e436daaf9fa13af1224212f7385f0
