### ISSUE TITLE
Cursor stutter after moving out of client

### ISSUE THREAD

**Issue by jonpas** [gnif/LookingGlass#323]
Some time between B2 and current master https://github.com/gnif/LookingGlass/commit/b942085e6c635c68dc0cd7bccfc134621c0f948c cursor became stuttery/freezy when moving from client window to another window out side of it. Beta 2 confirmed working fine.

It only seems to stutter when moving to an actual other window and not just in/out of Looking Glass client when it's positioned as floating above another window. This could just be a phantom effect though.

![image](https://user-images.githubusercontent.com/7935003/98938500-44c97c80-24e8-11eb-99d9-26dac33dd00f.png)

Can help isolate further by going through some possible commits to test and isolate the issue.

---

Host CPU: AMD Ryzen 7 3700X (16) @ 3.6 GHz
Host GPU: NVIDIA GeForce GT 710
Guest GPU: NVIDIA GeForce GTX 1060 6GB
Host Kernel version: `5.8.14-zen1-1-zen `
Host QEMU version: `5.1.0`
Host WM: i3

Looking Glass configuration:
```ini
[input]
escapeKey=109 ; SDL 'F18'

[spice]
host=/run/user/1000/spice.sock
port=0
```

**Comment by gnif** [comment]
Is synergy/barrier in use here? Can you please record and show exactly how it's behaving?

**Comment by jonpas** [comment]
Negative, I have tried with barrier/synergy disabled on host and guest.

It is hard to capture, as running OBS as well seems to reduce it. I managed to get this, at the start it works fine, then cursor starts freezing and my mouse circles are interrupted. At the end, it seems to recover mostly again.
[looking_glass_cursor.zip](https://github.com/gnif/LookingGlass/files/5531974/looking_glass_cursor.zip)

**Comment by gnif** [comment]
Can you please update the latest master as this has likely been fixed with the changes that went in over the last couple of days.

**Comment by jonpas** [comment]
Tried latest master, still happening. Maybe even a bit worse. It's very easily noticable if you shut down the VM and Looking Glass goes to splash screen, don't even have to move into the LG window, keeps stuttering on the host.

**Comment by daiaji** [comment]
I seem to have encountered a similar BUG.https://github.com/gnif/LookingGlass/issues/342

**Comment by gnif** [comment]
@daiaji  Your issue is completely different, please don't pollute other issue reports in the future.

**Comment by gnif** [comment]
@jonpas please update to the latest master, both the host and the client. This issue should be fixed now.

**Comment by jonpas** [comment]
Updated to https://github.com/gnif/LookingGlass/commit/9b309db9647a2b3a4b9921d37b058c64139b9b4f, that issue appeares to be resolved.

Lag of cursor inside Looking Glass is far worse now, to the point of random jumping of cursor without even moving the mouse. Made sure barrier or anything similar is not running. Both scaled or full-screen at same resolution as VM. Unsure if this could be linked to those fixes, so I can make a separate issue if that would be better.

**Comment by gnif** [comment]
Please update again, there was a bug in the last set of patches that I have now corrected.

**Comment by jonpas** [comment]
That works great now! I see no stutter anywhere, tried replicating the same issue in exact same configuration (or at least how much I could), works perfectly. Thanks!

**Comment by gnif** [comment]
Closing as fixed, thanks for testing!

**Comment by jonpas** [comment]
Glad to be of help!
